### ISSUE TITLE
Why are my libraries not updated?

### ISSUE THREAD

**Issue by xreef** [arduino/library-registry#1002]
Hi, 
I think I lost something, my library:
https://github.com/xreef/SimpleFTPServer
https://github.com/xreef/EByte_LoRa_E22_Series_Library

They are not automatically updated.
Bye Renzo

**Comment by per1234** [comment]
Hi @xreef

---

>https://github.com/xreef/SimpleFTPServer

Everything looks fine to me with this one:

https://downloads.arduino.cc/libraries/logs/github.com/xreef/SimpleFTPServer/

Your 1.0.0 release was rejected due to the unexpected name change, but I see you already corrected that and the last two releases have been accepted:

![image](https://user-images.githubusercontent.com/8572152/152352913-017e5f2e-d666-4d3a-9b28-602a1b9e79fc.png)

---

>https://github.com/xreef/EByte_LoRa_E22_Series_Library

This one has an error:

https://downloads.arduino.cc/libraries/logs/github.com/xreef/EByte_LoRa_E22_Series_Library/

```
Linting sketch in /home/ubuntu/workspace/gitclones/github.com/xreef/EByte_LoRa_E22_Series_Library/examples/Arduino_MKR_Nano_33_e22_05_sendFixedTransmissionStructurePartial
ERROR: File name(s): Arduino_MKR_Nano_33_e22_05_sendFixedTransmissionStructurePartial.ino exceed maximum length. See:   
       https://arduino.github.io/arduino-cli/latest/sketch-specification/#sketch-root-folder (Rule SS003)               
```

The maximum allowed sketch folder name length is 63 characters and this one is 64 characters. So you will need to reduce that.

My suggestion would be organize the examples into subfolders. Maybe something like:

```
examples
|_ Arduino
|_ Arduino_MKR_Nano_33
|_ esp32
|_ esp8266
```

Once the violation is corrected, you should make another release of the library:

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day. The non-compliant release will still be missing, but since the newer release will be available, that is no problem.

---

You might consider setting up an automated check in your library repository for compliance with the Library Manager requirements. This could run on every commit and pull request to ensure such violations are caught immediately.

Arduino provides a [GitHub Actions](https://docs.github.com/en/actions) action that makes this very easy to do by adding a simple YAML file to the repository:

https://github.com/arduino/arduino-lint-action#readme

This action uses the same [Arduino Lint](https://github.com/arduino/arduino-lint) tool as the Library Manager system.

It is in use in all the official Arduino library repositories ([example](https://github.com/arduino-libraries/Servo/blob/master/.github/workflows/check-arduino.yml)).

---

Please let me know if you have any questions or concerns.
Regards, Per

**Comment by xreef** [comment]
Hi @per1234,
thanks for all, I fixed It.
Thank again Renzo

**Comment by per1234** [comment]
You're welcome. I'm glad if I was able to be of assistance.

Regards, Per
