### ISSUE TITLE
Library name change request.

### ISSUE THREAD

**Issue by akkoyun** [arduino/library-registry#1100]
Hi,
Please change my library name to "I2C_Functions"

Library repo : https://github.com/akkoyun/I2C_Functions

**Comment by akkoyun** [comment]
hi, is there a problem my friends ? I m still waiting name change.

**Comment by per1234** [comment]
Hi @akkoyun. As I have already explained ([here](https://github.com/arduino/library-registry/pull/1084#issuecomment-1046251850), and [here](https://github.com/arduino/library-registry/pull/1087#issuecomment-1046527496)), name change requests are handled manually.

Although the submission process is 100% automated, the less common requests like name changes and removals are still done by a human maintainer. The change can not be made from this repository alone. In addition to the changes you see here, a person with access must make associated changes to the Library Manager database. For the sake of efficiency, they accommodate all the requests in a batch periodically rather than one by one as the requests come in.

They will close this issue when that is done and you will get a notification from GitHub at that time.

After that, there may be a delay of as much as a day for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN and local cache.

We'll surely get to it soon, please be patient.

**Comment by umbynos** [comment]
Done [here](https://github.com/arduino/library-registry/pull/1087#issuecomment-1059224552)
