### ISSUE TITLE
New Release Issue - Released the library before changing the version in the library.properties

### ISSUE THREAD

**Issue by MicroBeaut** [arduino/library-registry#1121]
@ArduinoBot

**Comment by per1234** [comment]
Hi @MicroBeaut 

## Problem

It sounds like you have already identified the problem, but I'll provide some information. You can see the situationhere in [the "MicroBeaut" library's dedicated indexer logs web page](https://downloads.arduino.cc/libraries/logs/github.com/MicroBeaut/MicroBeaut/):

```text
2022/02/24 23:22:22 Checking out tag: v1.2.0
2022/02/24 23:22:22 Release MicroBeaut:1.0.0 already loaded, skipping
```

Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `v1.2.0` tag (note that it checked out tag `v1.2.0`, but then found the release version was `1.0.0`).

You can see it here:

<https://github.com/MicroBeaut/MicroBeaut/blob/v1.2.0/library.properties#L2>

```text
version=1.0.0
```

Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the  `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata). For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

## Solution

The solution is to make another release of the library which meets [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list):

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day. The non-compliant release will still be missing, but since the newer release will be available, that is no problem.

Please let me know if you have any questions or concerns.
Regards, Per
