### ISSUE TITLE
Removing Repository Release

### ISSUE THREAD

**Issue by InqOnThat** [arduino/library-registry#1189]
Totally my fault.  New to using GitHub and didn't not read your FAQ before messing with my Repository at https://github.com/InqOnThat/InqPortal.  This is what I did...

1. deleted 5.1.1
2. created 5.1.2 - I think on 3/11
3. Although I see 5.1.2 in the log:  http://downloads.arduino.cc/libraries/logs/github.com/InqOnThat/InqPortal/
4. It never showed up in the Arduino IDE Library Manager
5. This is when I found the FAQ
6. I could not find a way to delete the tag as described in the FAQ at https://github.com/InqOnThat/InqPortal/tags
7. So I tried to re-create a 5.1.1 release, hoping that your system would detect it, but see that 5.1.2 now available.

Can you help me fix my problem?

**Comment by per1234** [comment]
Hi @InqOnThat 

## Problem

The problem is shown here in the logs:

```text
2022/03/15 07:22:32 Checking out tag: v5.1.2
2022/03/15 07:22:32 Release InqPortal:5.1.1 already loaded, skipping
```

Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `v5.1.2` tag (note that the indexer checked out tag `v5.1.2`, only to find the release version was `5.1.1`).

You can see it here:

<https://github.com/InqOnThat/InqPortal/blob/v5.1.2/library.properties#L2>

```text
version=5.1.1
```

Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the  `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata). For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

## Solution

The solution is to make another release of the library which meets [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list):

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day. The non-compliant release will still be missing, but since the newer release will be available, that is no problem.

Please let me know if you have any questions or concerns.
Regards, Per
