### ISSUE TITLE
Questions about the creation of libraries

### ISSUE THREAD

**Issue by Tinyu-Zhao** [arduino/library-registry#1277]
Hello, because our product type is rich, so the peripherals available for microcontrollers are also more, recently there is a user feedback because one of our microcontroller long pants added too many peripheral dependencies, and its screen is too small, so that the whole screen display can not be, there is no way to do any operation.

![IMG_2243](https://user-images.githubusercontent.com/44396641/162421771-03daddbb-1fac-4d93-b448-bc31179441fe.PNG)

So we want to create a dependency repository to store all the dependencies, and then the microcontroller depends on this "dependency" library to arrive at the download time to recursively download all the dependent items

[Just like this repositories](https://github.com/Tinyu-Zhao/M5-Depends/blob/main/library.properties)
Then fill in the dependencies in the M5Stack repository as "M5-Depends"

The dependence of one of our microcontrollers [M5Stack](https://github.com/m5stack/M5Stack/blob/16db1b0b14982e89cf0def79be5f1bf682ccfc17/library.properties#L11)

**Comment by per1234** [comment]
Hi @Tinyu-Zhao. You are welcome to submit such a "dependencies container" library as long as it meets [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-a-library-to-be-added-to-library-manager).

Arduino even has one that is used to define the "built-in" libraries that should be automatically installed on the first run of Arduino IDE 2.x. You can use that as a reference:

https://github.com/arduino-libraries/Arduino_BuiltIn

---

Unfortunately, this will not serve as a workaround for the bug with the Arduino IDE 1.x dependencies installation dialog (https://github.com/arduino/Arduino/issues/10647). The reason is that the dialog lists transitive dependencies. So even if you change [the `depends` field](https://github.com/m5stack/M5Stack/blob/16db1b0b14982e89cf0def79be5f1bf682ccfc17/library.properties#L11) in the `library.properties` file of the "M5Stack" library to:

```
depends=M5-Depends
```

The Arduino IDE Library Manager dependencies installation dialog for the "**M5Stack**" library will still display all the transitive dependencies from the "**M5-Depends**" library. So the effect will actually be to add one more dependency to the list.

---

I am happy to tell you that Arduino IDE 2.x does correctly handle this situation by making the dependencies list scrollable when it exceeds the available display space:

![image](https://user-images.githubusercontent.com/8572152/162429764-6faca867-a70c-44ff-9a14-19f7cf4b75b0.png)

Unfortunately, the users of Arduino IDE 1.x will continue to be affected by https://github.com/arduino/Arduino/issues/10647 until an equivalent fix is made there.

Since we are already tracking the Arduino IDE 1.x dependencies dialog bug at https://github.com/arduino/Arduino/issues/10647, I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

---

FYI, I see that the "**M5Stack**" library is affected by a separate bug in Arduino IDE 2.x: https://github.com/arduino/arduino-ide/issues/621, and this is something you can easily fix by:

1. Correct the `depends` field of the "**M5Stack**" library so that it only contains libraries that are available from Library Manager.
1. Make a new release of the "**M5Stack**" library.
