### ISSUE TITLE
I2C_LCD12864

### ISSUE THREAD

**Issue by andhieSetyabudi** [arduino/library-registry#1485]
### Library repository URL

https://github.com/andhieSetyabudi/MCP23017_LCD12864

**Comment by per1234** [comment]
Hi @andhieSetyabudi. I see you are requesting the name of your library be updated.

The registered name is "I2C_LCD12864":

https://github.com/arduino/library-registry/blob/91772dbaf19dcf944480729707b50c7b46659b57/registry.txt#L4596

And the name defined the the metadata of the library is also "I2C_LCD12864":

https://github.com/andhieSetyabudi/MCP23017_LCD12864/blob/b8021e9b953eb48e2dccceeb22fabaa1966a0d1b/library.properties#L1

```text
name= I2C_LCD12864
```

Since no renaming is necessary, I will close this issue as resolved.

Please let me know if you have any questions or concerns.
Per
