### ISSUE TITLE
The lib didn't update after new tag drafted

### ISSUE THREAD

**Issue by Forairaaaaa** [arduino/library-registry#1486]
Hi,
I update my lib to a new tag few days ago, but i still can't see the update in the ArduinoIDE. So, I tried draft a new tag hours ago, but ArduinoIDE still maintains the old version of the lib. Could you please have a check and point out where I did wrong?
https://github.com/m5stack/M5-CoreInk.git
Thanks

**Comment by per1234** [comment]
Hi @Forairaaaaa 

## Problem

The problem is shown here in [the "M5-CoreInk" library's dedicated indexer logs web page](https://downloads.arduino.cc/libraries/logs/github.com/m5stack/M5-CoreInk/):

```text
2022/06/13 08:18:22 Checking out tag: 0.0.4
2022/06/13 08:18:23 Release M5-CoreInk:0.0.3 already loaded, skipping
```

Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `0.0.4` tag (note that the indexer checked out tag `0.0.4`, only to find the release version was `0.0.3`).

You can see it here:

<https://github.com/m5stack/M5-CoreInk/library.properties#L2>

```text
version=0.0.3
```

Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the  `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata). For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

## Solution

The solution is to make another release of the library which meets [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list):

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day. The non-compliant release will still be missing, but since the newer release will be available, that is no problem.

Please let me know if you have any questions or concerns.
Regards, Per

**Comment by Forairaaaaa** [comment]
Thanks a lot! I'll try again.

**Comment by Forairaaaaa** [comment]
> Hi @Forairaaaaa
> 
> ## Problem
> The problem is shown here in [the "M5-CoreInk" library's dedicated indexer logs web page](https://downloads.arduino.cc/libraries/logs/github.com/m5stack/M5-CoreInk/):
> 
> ```
> 2022/06/13 08:18:22 Checking out tag: 0.0.4
> 2022/06/13 08:18:23 Release M5-CoreInk:0.0.3 already loaded, skipping
> ```
> 
> Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `0.0.4` tag (note that the indexer checked out tag `0.0.4`, only to find the release version was `0.0.3`).
> 
> You can see it here:
> 
> https://github.com/m5stack/M5-CoreInk/library.properties#L2
> 
> ```
> version=0.0.3
> ```
> 
> Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata). For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.
> 
> ## Solution
> The solution is to make another release of the library which meets [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list):
> 
> 1. Update the `version` value in `library.properties` to the version that will be used for the new release.
> 2. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
> 
> The indexer system will pick up that new release and it will be available from Library Manager within a day. The non-compliant release will still be missing, but since the newer release will be available, that is no problem.
> 
> Please let me know if you have any questions or concerns. Regards, Per

Thanks a lot! I'll try again.
