### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by Mosiwi** [arduino/library-registry#1539]
### Library name

Mosiwi-basic-learning-kit-for-arduino

### Version to remove

v1.0.0

**Comment by per1234** [comment]
Hi @Mosiwi. You must delete the [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) from the library's repository before we can remove the release. I see that it has not yet been removed.

I'll provide instructions you can follow to do that:

1. Click the following link to open the web page of the tag:
   https://github.com/Mosiwi/Mosiwi-basic-learning-kit-for-arduino/releases/tag/v1.0.0
1. Click the <kbd>**Delete**</kbd> button on that page.
1. Click the <kbd>**I understand, delete this tag**</kbd> button.
1. Comment here to let me know that the tag has been deleted so that I can proceed with removing the release from Arduino Library Manager.

**Comment by Mosiwi** [comment]
Hello, v1.0.0 has now been deleted.

**Comment by per1234** [comment]
Thanks! I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues and pull requests when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by Mosiwi** [comment]
Hello, I updated the code of the library, changed the version number, and released the new tag. Why is the Arduino library manager still not updated?

**Comment by per1234** [comment]
The problem is reported here on the dedicated logs webpage we publish for each library in the Arduino Library Manager:

http://downloads.arduino.cc/libraries/logs/github.com/Mosiwi/Mosiwi-basic-learning-kit-for-arduino/

```text
2022/06/26 02:22:36 Checking out tag: v2.0.0
2022/06/26 02:22:37 Release Mosiwi_Basic_Learning_Kit:2.0.0 has wrong library name, should be Mosiwi Basic Learning Kit
```

You changed the value of the `name` field in your `library.properties` metadata field from the one the library was registered under ("Mosiwi Basic Learning Kit"):

https://github.com/Mosiwi/Mosiwi-basic-learning-kit-for-arduino/blob/v2.0.0/library.properties#L1

```text
name=Mosiwi_Basic_Learning_Kit
```

As explained here, we do not accept any releases under a different name because this is the unique identifier for the library:

https://github.com/arduino/library-registry/blob/main/FAQ.md#update-requirements

**Comment by Mosiwi** [comment]
Hello, it has been changed to the correct name, thank you for your help.
