### ISSUE TITLE
The latest version was not found in the Arduino Library Manager after the release

### ISSUE THREAD

**Issue by Tinyu-Zhao** [arduino/library-registry#1552]
The latest version was not found in the Arduino Library Manager after the release.
I followed the tutorial to query the logs but didn't find any exceptions, please help me.
http://downloads.arduino.cc/libraries/logs/github.com/Tinyu-Zhao/M5-Depends/

**Comment by per1234** [comment]
Hi @Tinyu-Zhao.

## Problem

The problem is shown here in [the "M5-Depends" library's dedicated indexer logs web page](https://downloads.arduino.cc/libraries/logs/github.com/Tinyu-Zhao/M5-Depends/):

```text
2022/07/01 01:22:34 Checking out tag: 0.0.3
2022/07/01 01:22:34 Release M5-Depends:0.0.1 already loaded, skipping
```

Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `0.0.3` tag (note that the indexer checked out tag `0.0.3`, only to find the release version was `0.0.1`).

You can see it here:

<https://github.com/Tinyu-Zhao/M5-Depends/blob/0.0.3/library.properties#L2>

```text
version=0.0.1
```

Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata).

For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

## Solution

The solution is to make another release of the library which meets [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list):

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day.

The non-compliant release will still be missing, but since the newer release will be available, that is no problem.

Please let me know if you have any questions or concerns.
Regards, Per

**Comment by Tinyu-Zhao** [comment]
Thank you for your help!
