### ISSUE TITLE
WisBlock Audio Library added, but not visible in the library manager of Arduino IDE

### ISSUE THREAD

**Issue by beegee-tokyo** [arduino/library-registry#1813]
We published the [WisBlock Arduino Library](https://github.com/RAKWireless/RAKwireless-Audio-library) but it is not showing in the ArduinoIDE.

What does this error message mean:
```
2022/09/07 01:23:47 Scraping https://github.com/RAKWireless/RAKwireless-Audio-library.git
2022/09/07 01:23:49 Error fetching repository: reference delta not found
2022/09/07 01:23:49 Removing clone and trying again
2022/09/07 01:23:52 Error fetching repository: reference delta not found
2022/09/07 01:23:52 Leaving...
```
How can I solve it? I don't know what **`reference delta not found`** means.

**Comment by per1234** [comment]
Hi @beegee-tokyo. I explained the situation here: https://github.com/arduino/library-registry/pull/1792#issuecomment-1238822950

For any further discussion, please use the original issue https://github.com/arduino/libraries-repository-engine/issues/109 so that we can keep all information about the bug consolidated in a single place.
