### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by richard26a** [arduino/library-registry#1880]
### Library name

LED_Controls

### Version to remove

1.1.0

**Comment by per1234** [comment]
Hi @richard26a. You must delete the [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) from the library's GitHub repository before we can remove the release. I see that it has not yet been removed.

I'll provide instructions you can follow to do that:

1. Click the following link to open the GitHub page of the tag:
   [](https://github.com/richard26a/LED_Controls/releases/tag/trial)
1. Click the <kbd>**Delete**</kbd> button on that page.
1. Click the <kbd>**I understand, delete this tag**</kbd> button.
1. Comment here to let me know that the tag has been deleted so that I can proceed with removing the release from Arduino Library Manager.

**Comment by per1234** [comment]
Closing due to lack of response.

@richard26a if you ever get around to deleting [the tag](https://github.com/richard26a/LED_Controls/releases/tag/trial) as is required for us to accommodate this request, please comment here, I'll be happy to re-open this issue at that time.
