### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by botletics** [arduino/library-registry#2041]
### Library name

Botletics-SIM7000

### Version to remove

1.0.0

**Comment by botletics** [comment]
There was a small error that resulted in a compile error in 1.0.0. I fixed it, deleted the release, then created it again. Do I have to create 1.0.1, or can you just use the new 1.0.0?

**Comment by per1234** [comment]
Hi @botletics

>Do I have to create 1.0.1, or can you just use the new 1.0.0?

You should delete the 1.0.0 tag and create a 1.0.1 release according to these instructions:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

The reason is it would be very confusing for the users and maintainers of the library that the ones who install 1.0.0 before the removal operation have different library content than the ones who install 1.0.0 after. The point of releases is to create a reference to a specific point in the development history of the project.

**Comment by botletics** [comment]
Got it, thank you! I created 1.0.1

**Comment by umbynos** [comment]
Done:
```
2022/11/09 10:20:49 Loaded 5293 libraries from DB
Removing BotleticsSIM7000@1.0.0
Success!
```
