### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by JohnScottUK** [arduino/library-registry#2111]
### Library repository URL

https://github.com/jsware/able-buttons

**Comment by per1234** [comment]
Hi @JohnScottUK. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by JohnScottUK** [comment]
Hi @per1234 
Any idea how often the maintainer clears out requests. Will it be days/weeks? Happy to delete and re-add the library under the new name if that's a better option.

**Comment by per1234** [comment]
I don't have any estimate of the timeline for handling the request. You can check the previous requests to get an idea though.

>Happy to delete and re-add the library under the new name if that's a better option.

It would not make any difference because deletion requests also must be handled by the maintainer. It would actually be slower due to the additional time for submitting the library again.

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/2112#issuecomment-1333539224
