### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by STONElibrary** [arduino/library-registry#2327]
### Library name

Stone_serial

### Version to remove

1.0.8

**Comment by per1234** [comment]
Hi @STONElibrary. You must delete the `v1.0.8` [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) from the library's GitHub repository before we can remove the release. I see that it has not yet been removed.

I'll provide instructions you can follow to do that:

1. Click the following link to open the GitHub page of the tag:
   https://github.com/STONElibrary/arduino_lib/releases/tag/v1.0.8
1. Click the <kbd>**Delete**</kbd> button on that page.
1. Click the <kbd>**I understand, delete this tag**</kbd> button.
1. Comment here to let me know that the tag has been deleted so that I can proceed with removing the release from Arduino Library Manager.

**Comment by per1234** [comment]
Hi @STONElibrary. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/01/25 17:02:18 Loaded 5514 libraries from DB
Removing Stone_serial@1.0.8
Success!
```
