### ISSUE TITLE
Can you please update RV8803Tiny

### ISSUE THREAD

**Issue by dattasaurabh82** [arduino/library-registry#258]
Dear maintainer

I recently added a library : RV8803Tiny
I seems loaded:
![Screenshot 2021-07-21 at 8 58 36 PM](https://user-images.githubusercontent.com/4619862/126496491-18cfd6c3-2e32-4a3f-8a3f-b28cb65a4354.png)
![Screenshot 2021-07-21 at 9 25 46 PM](https://user-images.githubusercontent.com/4619862/126496307-4a43b189-26f9-4a1d-90c5-e89ec06bc9e2.png)

But I still can't find it in Library Manager:
![Screenshot 2021-07-21 at 8 58 09 PM](https://user-images.githubusercontent.com/4619862/126496394-39571385-729c-4e46-ac53-1eaa0fc24ed3.png)

Also an older version needs to be removed: 
![Screenshot 2021-07-21 at 8 58 16 PM](https://user-images.githubusercontent.com/4619862/126496471-68010e9a-04cd-478e-a18a-9b3333c3eb7e.png)
This is not the correct one that shows up ...

**Comment by per1234** [comment]
>But I still can't find it in Library Manager:

There is caching both in the CDN and in the Arduino IDE. As the bot explained in its comment to your pull request, it may take up to a day before you see the library appear in the Arduino IDE's Library Manager.

>Also an older version needs to be removed:

I explained everything in your pull request to remove the library:
https://github.com/arduino/library-registry/pull/251#issuecomment-883557634

Since library removals are a manual process, there will be a delay of a few weeks before the library index maintainer will have time to get to it. Please subscribe to the linked pull request so you can get a notification when it has been done: https://github.com/arduino/library-registry/pull/252
