### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by dojyorin** [arduino/library-registry#2779]
### Library repository URL

https://github.com/dojyorin/arduino_percent

**Comment by per1234** [comment]
Hi @dojyorin. I see you are requesting to change the registered library name to "**arduino_percent**":

https://github.com/dojyorin/arduino_percent/blob/v2.0.0/library.properties#L1

This particular name is not allowed because only libraries maintained by Arduino are permitted to be registered with names starting with "arduino".

If you would still like to change the registered library name, please do the following things:

1. Change the [`name` value](https://github.com/dojyorin/arduino_percent/blob/master/library.properties#L1) in the `library.properties` file to a unique name that is compliant with the requirements:
   https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format
1. Update the [`version` value](https://github.com/dojyorin/arduino_percent/blob/master/library.properties#L3) in the `library.properties` file to the version of the new release.
1. Make a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
1. Comment here to let us know we can proceed with the renaming.

If you decide you no longer wish to change the registered name of the library, you can close this issue.

---

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by dojyorin** [comment]
Sorry, I forgot to check the naming conventions.
I'll correct https://github.com/arduino/library-registry/issues/2778 as well.

**Comment by per1234** [comment]
OK, great. Please comment here once you have updated the name so we'll know we can proceed.

**Comment by dojyorin** [comment]
Sorry for the wait, I fixed the library name. (https://github.com/arduino/library-registry/issues/2778 also fixed.)
Regards.

**Comment by per1234** [comment]
Hi @dojyorin. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/05/16 15:38:45 Loaded 5845 libraries from DB
Removing Percent_Codec
Success!
```
