### ISSUE TITLE
RV8803Tiny & TinyMegaI2C have not loaded to latest versions yet

### ISSUE THREAD

**Issue by dattasaurabh82** [arduino/library-registry#286]
Dear admin. 
Can you please check the status of these two libraries: 
1. [TinyMegaI2C ](https://github.com/dattasaurabh82/TinyMegaI2C) [Latest release **0.0.2**]
2. [RV8803Tiny](https://github.com/dattasaurabh82/RV8803Tiny) (dependent on TinyMegaI2c)  [Latest release **0.0.3**]

The status is they are still not available in the Library manager.
I get the status they are loaded and it's been more than 24 hours or so, but the respective latest versions are still not available and I don't see much info in the logs as well (listed below) if there were issues.  

```
2021/07/26 18:59:34 Scraping https://github.com/dattasaurabh82/TinyMegaI2C.git
2021/07/26 18:59:35 Checking out tag: 0.0.1
2021/07/26 18:59:35 Release TinyMegaI2C:0.0.1 already loaded, skipping
2021/07/26 18:59:35 Checking out tag: 0.0.2
2021/07/26 18:59:35 Release TinyMegaI2C:0.0.1 already loaded, skipping
```

```
2021/07/26 15:59:27 Scraping https://github.com/dattasaurabh82/RV8803Tiny.git
2021/07/26 15:59:27 Checking out tag: 0.0.1
2021/07/26 15:59:27 Release RV8803Tiny:0.0.1 already loaded, skipping
2021/07/26 15:59:27 Checking out tag: 0.0.2
2021/07/26 15:59:27 Release RV8803Tiny:0.0.2 already loaded, skipping
2021/07/26 15:59:27 Checking out tag: 0.0.3
2021/07/26 15:59:27 Release RV8803Tiny:0.0.2 already loaded, skipping

```

**Comment by per1234** [comment]
>they are still not available in the Library manager

Hi @dattasaurabh82. The problem is that you forgot to update the `version` field of the `library.properties` metadata file before making the tag.

You can see here that the `version` is still set to "0.0.1" in your 0.0.2 tag of TinyMegaI2C:
https://github.com/dattasaurabh82/TinyMegaI2C/blob/0.0.2/library.properties#L2
```
version=0.0.1
```
Same problem with RV8803Tiny's 0.0.3 tag:
https://github.com/dattasaurabh82/RV8803Tiny/blob/0.0.3/library.properties#L2
```
version=0.0.2
```

Even though the unit of library releases in Arduino Library Manager is the Git tag, all versioning of those releases is based on the library.properties `version` value. The name of the Git tag is not at all a factor in versioning. It's only an arbitrary identifier for that point in the Git history.

In order to be accepted into the Arduino Library Manager index, a library release is required to have a unique `version` value. Any release with a duplicate `version` value is rejected.

So you will need to do the following:

1. Bump the `version` value in library.properties.
2. Create a  new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.


---
> I don't see much info in the logs as well (listed below) if there were issues.

If you look closely at the logs, you can see that it reports the problem:
```
2021/07/26 18:59:35 Checking out tag: 0.0.2
2021/07/26 18:59:35 Release TinyMegaI2C:0.0.1 already loaded, skipping
```
Note the "0.0.1" in the "Release TinyMegaI2C:0.0.1 already loaded, skipping" log message, but it is quite subtle. Since this is the most common cause of library release rejection, I would like to make the library engine's communication more effective in this situation. I hope to get some time allocation to work on that in the near future.

**Comment by dattasaurabh82** [comment]
Ah shit! 😶
That's why my math teacher in school was always annoyed of my super silly mistakes!. 🤬

Thanks for the response and explanation. 😌
Much appreciated!

**Comment by per1234** [comment]
You're welcome. I'm glad if I was able to be of assistance.

Regards, Per
