### ISSUE TITLE
possible missing content in readme

### ISSUE THREAD

**Issue by jmerc77** [arduino/library-registry#2988]
### Describe the problem

I couldn't find info on what to do with the branch after successful PR to the list. maybe I overlooked it but please add if missing. if I did over look, point it out please. also this was my first PR ever that I noticed this.

### To reproduce

looking at the readme. then pondering what to do about the branch. thinking, "is it truly safe to delete?"

### Expected behavior

the info should be there. whether or not its OK to delete the branch after successful PR.

### Additional context

FYI, I left the branch there for now.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @jmerc77. Thanks for your report. The branch is the property of your own GitHub account. You are free to do with it as you like just as in any other repository under your account. The pull request is your proposal for a change to be made to Arduino's repository. When the pull request is merged, the proposed changes are introduced into Arduino's repository. After that, any actions you take in the branch the pull request was staged from don't have any effect on Arduino's repository (unless you submit a new pull request from that branch).

The documentation in this repository is primarily focused on providing the information that is specific to using this repository's unique systems. We do include the steps necessary to submit a pull request, but the documentation is not intended to be a comprehensive guide to using GitHub's pull request feature. There is a lot of existing information about that subject outside this repository, and a link to some of that information is included in the documentation here:

https://github.com/arduino/library-registry#adding-a-library-to-library-manager

> If you would like to make a library available for installation via Library Manager, just submit a [pull request](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests) ...

So since no specific action is required of the user in regards to their branch or fork, and since that subject is universal to any pull request, I don't see the need to include it in this repository's documentation.

---

To answer your doubts, you are welcome to delete your branch after the pull request has been merged. I would even recommend you to delete your fork entirely. The reason you might want to delete branches and forks after they no longer have any purpose is to keep your repositories and GitHub account tidy.  If you don't do that, then your repositories will accumulate pointless branches over time as you work in the repositories and your account will accumulate pointless forks over time as you submit pull requests to other repositories. But an accumulation of pointless branches and forks is not terribly harmful so you are also welcome to leave the fork and branch as it is if you don't care about tidiness.
