### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by josiascarnot** [arduino/library-registry#3037]
### Library name

YoupiLabEsp32

### Version to remove

1.0.0

**Comment by josiascarnot** [comment]
Bonsoir

**Comment by per1234** [comment]
Hi @josiascarnot. You must delete the [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) from the library's GitHub repository before we can remove the release. I see that it has not yet been removed.

I'll provide instructions you can follow to do that:

1. Click the following link to open the GitHub page of the tag:
   https://github.com/YoupiLab/YoupiLabEsp32/releases/tag/1.0.0
1. Click the <kbd>**Delete**</kbd> button on that page.
1. Click the <kbd>**I understand, delete this tag**</kbd> button.
1. Comment here to let me know that the tag has been deleted so that I can proceed with removing the release from Arduino Library Manager.

**Comment by josiascarnot** [comment]
Hello i remove already

**Comment by josiascarnot** [comment]
hello i remove release already

**Comment by per1234** [comment]
@josiascarnot the tag is still there in the library's GitHub repository:

https://github.com/YoupiLab/YoupiLabEsp32/releases/tag/1.0.0

Please carefully follow the instructions I provided in my previous reply.

**Comment by josiascarnot** [comment]
Sorry i remove now

**Comment by per1234** [comment]
Hi @josiascarnot. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by per1234** [comment]
I see now that there is another tag named `ylesp` in the repository that the Library Manager indexer will use as the 1.0.0 release even after you deleted the `1.0.0` tag (it is the `version` field of the library.properties file that sets the version number for the release, not the tag name). That tag must be removed also:

I'll provide instructions you can follow to do that:

1. Click the following link to open the GitHub page of the tag:
   https://github.com/YoupiLab/YoupiLabEsp32/releases/tag/ylesp
1. Click the <kbd>**Delete**</kbd> button on that page.
1. Click the <kbd>**I understand, delete this tag**</kbd> button.
1. Comment here to let me know that the tag has been deleted so that I can proceed with removing the release from Arduino Library Manager.

**Comment by josiascarnot** [comment]
it is done

**Comment by per1234** [comment]
Hi @josiascarnot. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by josiascarnot** [comment]
Hello

**Comment by josiascarnot** [comment]
Hello

**Comment by josiascarnot** [comment]
Supression takes quite a long time, so I'd like to know how long I have to wait for my request to be executed.

**Comment by per1234** [comment]
@josiascarnot I don't have any information for you about when your request will be accommodated. Please be patient. I can assure you that spamming this thread with messages is not productive.

But really, removing a release from Library Manager is something that should only be necessary in very rare cases where the release contains something that absolutely must not be distributed such as a bug that might cause permanent damage to the Arduino board or peripherals. In all other cases, the professional development practice is to simply release a new version (e.g., 1.0.1) with whatever improvements or fixes you want to distribute to the users.

We allow requests for removal of releases because we understand that there might be some exceptional circumstances where this is truly needed, but you should understand that if the maintainer of every one of the thousands of libraries requested removals of releases for trivial reasons and nagged us about it then we would need to withdraw the offer to accommodate such requests so you behaving irresponsibly here.

**Comment by MatteoPologruto** [comment]
Done:
```
2023/07/18 12:35:25 Loaded 5988 libraries from DB
Removing YoupiLabEsp32@1.0.0
Success!
```
