### ISSUE TITLE
New version not showing up

### ISSUE THREAD

**Issue by tedtoal** [arduino/library-registry#3090]
My library, monitor_printf, released the initial time with V1.1.1, but subsequent versions do not.  The log shows:

```
2023/07/18 12:29:43 Scraping https://github.com/tedtoal/monitor_printf.git
2023/07/18 12:29:43 Checking out tag: V1.1.1
2023/07/18 12:29:43 Release monitor_printf:1.1.1 already loaded, skipping
2023/07/18 12:29:43 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) has suggestions for possible improvements:
Click to expand Arduino Lint report

2023/07/18 12:29:43 Checking out tag: V1.2.1
2023/07/18 12:29:43 Release monitor_printf:1.1.1 already loaded, skipping
2023/07/18 12:29:43 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) has suggestions for possible improvements:
Click to expand Arduino Lint report

2023/07/18 12:29:43 Checking out tag: V1.3.1
2023/07/18 12:29:43 Release monitor_printf:1.1.1 already loaded, skipping
2023/07/18 12:29:43 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) has suggestions for possible improvements:
Click to expand Arduino Lint report

2023/07/18 12:29:43 Checking out tag: V1.4.1
2023/07/18 12:29:43 Release monitor_printf:1.4.1 already loaded, skipping
2023/07/18 12:29:43 Checking out tag: V1.5.1
2023/07/18 12:29:43 Release monitor_printf:1.5.1 already loaded, skipping
```

The V1.3.1 release I made specifically to try to get it to update, making no changes other than updating the release number library.properties and then creating the release and the tag V1.3.1.

I have not renamed the library.

Why is it not creating new releases?

**Comment by per1234** [comment]
Hi @tedtoal.

The problem is shown here in [the logs](https://downloads.arduino.cc/libraries/logs/github.com/tedtoal/monitor_printf/):

```text
2023/07/18 12:29:43 Checking out tag: V1.2.1
2023/07/18 12:29:43 Release monitor_printf:1.1.1 already loaded, skipping
2023/07/18 12:29:43 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) has suggestions for possible improvements:
Click to expand Arduino Lint report

2023/07/18 12:29:43 Checking out tag: V1.3.1
2023/07/18 12:29:43 Release monitor_printf:1.1.1 already loaded, skipping
2023/07/18 12:29:43 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) has suggestions for possible improvements:
Click to expand Arduino Lint report
```

Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `V1.2.1` and `V1.3.1` tags (note that the indexer checked out tag `V1.2.1`, only to find the release version was `1.1.1`, and the same when checking out the `V1.3.1`).

You can see it here:

<https://github.com/tedtoal/monitor_printf/blob/V1.2.1/library.properties#L2>

```text
version=1.1.1
```

<https://github.com/tedtoal/monitor_printf/blob/V1.3.1/library.properties#L2>

```text
version=1.1.1
```

Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata).

For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

---

I see you have already followed the correct procedure when making the 1.4.1 and 1.5.1 releases, and that those have already been indexed by the Library Manager system, so no action is needed. Just be very careful to follow the correct procedure when making future releases of your library.
