### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by Gitshaoxiang** [arduino/library-registry#3124]
### Library name

M5Family

### Version to remove

0.0.9

**Comment by Gitshaoxiang** [comment]
I had remove the tag one time. then release again. but even it could be searched in the library manager, but seems I can't download it.

**Comment by per1234** [comment]
Hi @Gitshaoxiang. A release tag is expected to be an immutable marker at a specific point in the repository history. It is a bad idea to ever move a release tag:

https://git-scm.com/docs/git-tag#_on_re_tagging

The problem is that anyone who already installed 0.0.9 before the re-tag would have one version of the library code, while everyone who installed it after the re-tag will have a different version. That will create an incredibly confusing situation for the users and library maintainers.

What you should do instead is simply make a new release (e.g., 0.0.10) to distribute whatever changes you originally intended to distribute via the 0.0.9 release. The 0.0.9 release will still be available for installation via Library Manager, but that isn't a problem because Library Manager always offers the latest release by default so the users will install 0.0.10.

If there is something in the 0.0.9 release that absolutely must not be distributed, then you can permanently delete that tag from the repository and then submit another release removal request. But please note this sort of request should only be made under exceptional circumstances because it requires a manual process for us to accommodate such requests and if there is widespread unnecessary submissions of such requests by the maintainers of the >5000 libraries in Library Manager, we would be forced to change our policies to no longer allow release removal requests.
