### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by stlljonas** [arduino/library-registry#3227]
### Library repository URL

https://github.com/sensirion/arduino-uart-svm4x

**Comment by per1234** [comment]
Hello @stlljonas. I see the library name has been changed in the metadata:

https://github.com/Sensirion/arduino-uart-svm4x/commit/17971a5ea86dc60cf0de6ef82563bd21afa91157

However, Library Manager works exclusively from Git tags, and there hasn't been a tag since the time of the change to the metadata. So the indexer engine will only find a release under the old name:

https://github.com/Sensirion/arduino-uart-svm4x/blob/0.1.0/library.properties#L1

```text
name=Sensirion UART Svm41
```

Please create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

Once you have done that, add a comment here so we'll know we can proceed with the name change.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by stlljonas** [comment]
Hi Per, thanks so much for the pointers. I've just added a 0.2.0 tag to the library, see https://github.com/Sensirion/arduino-uart-svm4x/releases/tag/0.2.0. Best, Jonas

**Comment by per1234** [comment]
Hi @stlljonas. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/08/23 11:50:39 Loaded 6126 libraries from DB
Removing Sensirion UART Svm41
Success!
```
