### ISSUE TITLE
update library

### ISSUE THREAD

**Issue by pranavdhage** [arduino/library-registry#328]
#311

**Comment by per1234** [comment]
Hi @pranavdhage. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically! It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
http://downloads.arduino.cc/libraries/logs/github.com/dhi-nikhil/indhi-lib-arduino-esp32/
If you look there, you will see that your 1.0.1 release has already been indexed

**Comment by pranavdhage** [comment]
Thanks for replaying,
I actually want to apply patch to my release version 1.0.1
link to repo : https://github.com/dhi-nikhil/indhi-lib-arduino-esp32
I have created new release with the same version but the library manager is not picking it.

**Comment by per1234** [comment]
This is not allowed. You can only make a release once. The reason is because it would be very confusing for users to be getting different results depending on which variant of 1.0.1 they happen to have installed. Releases are meant to be an immutable snapshot of a point in the library's development history.

You should simply make a new release. Library Manager defaults to installing the latest version of the library and offers updates to those with an older version installed, so this is a fast and effective method for distributing a fix to the users.
