### ISSUE TITLE
Library maintainer change request

### ISSUE THREAD

**Issue by Khuuxuanngoc** [arduino/library-registry#3434]
### Library repository URL

https://github.com/makerlabvn/Makerlabvn_I2C_Motor_Driver.git

**Comment by Khuuxuanngoc** [comment]
Hi, please help to change [Maintainer] from "Ngoc" to "Makerlab.vn"
![image](https://github.com/arduino/library-registry/assets/8817696/49e5359d-c945-4906-8b52-48381c12fe49)

I tried to release the new version (v1.0.5) but it is invisible

**Comment by per1234** [comment]
Hi @Khuuxuanngoc. Due to CDN and local caching of the index file, it can take some time between when the indexer processes a new release and when it becomes available in the Library Manager. We give a conservative estimate of availability to everyone within one day's time.

I can see that everything is as expected in my Library Manager:

![image](https://github.com/arduino/library-registry/assets/8572152/932aa238-9a4a-43ad-a724-be99f17a2405)

![image](https://github.com/arduino/library-registry/assets/8572152/01f7e186-a32f-4180-ac9d-2dd5d673e7e4)

I think you will find the same if you check again.

**Comment by Khuuxuanngoc** [comment]
> Hi @Khuuxuanngoc. Due to CDN and local caching of the index file, it can take some time between when the indexer processes a new release and when it becomes available in the Library Manager. We give a conservative estimate of availability to everyone within one day's time.
> 
> I can see that everything is as expected in my Library Manager:
> 
> ![image](https://user-images.githubusercontent.com/8572152/273417493-932aa238-9a4a-43ad-a724-be99f17a2405.png)
> 
> ![image](https://user-images.githubusercontent.com/8572152/273417494-01f7e186-a32f-4180-ac9d-2dd5d673e7e4.png)
> 
> I think you will find the same if you check again.

Thank you for your response!
