### ISSUE TITLE
 [Library Manager] please remove the TelnetStream2 library #10831 

### ISSUE THREAD

**Issue by rin67630** [arduino/library-registry#3889]
Please reconsider purging this confusing library.
The Author of TelnetStream2 admitted having changed nothing in his fork and just published TelnetStream2 to force an inclusion in the LibraryManager.
Now that the original Telnetstream is present and a few versions further, the Telnetstream2 is only confusing.
I am not affiliated with the Authors, am just an user that lost time clarifying what is behind TelnetStream2: nothing but an obsolete fork.

**Comment by per1234** [comment]
Thanks for taking the time to make this request @rin67630. I appreciate your care for the quality of the Library Manager libraries. However, Arduino's policy is that we only remove libraries under one of the following conditions:

- The maintainer of the library has approved the removal
- There is conclusive proof that the library contains illegal material (e.g., copyright violation)
- There is conclusive proof of malicious content

Since none of these conditions have been met, I will have to decline this.

You are welcome to work with @ameer1234567890 to find a resolution.

If they agree to the removal then you are welcome to submit another [removal request](https://github.com/arduino/library-registry#removing-a-library-from-library-manager), making sure to provide evidence of the removal in order to enable the registry maintainer to validate its legitimacy.
