### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by koendv** [arduino/library-registry#4077]
### Library repository URL

https://github.com/koendv/FloatToString

**Comment by koendv** [comment]
Renamed https://github.com/koendv/FloatToString to https://github.com/koendv/FloatToAscii to avoid collision with https://github.com/tedtoal/floatToString

**Comment by per1234** [comment]
Hi @koendv. I see that you have created a whole new repository for the "FloatToAscii" library. Since the library has a new name and a new repository, it would be considered a separate library for our purposes (even if the code is equivalent).

For this reason, I think the most appropriate procedure will be for you to:

- Submit a removal request for the the "FloatToString" library (following [**this procedure**](https://github.com/arduino/library-registry#removing-a-library-from-library-manager)).
- Submit the "FloatToAscii" library for addition to Library Manager (following [**this procedure**](https://github.com/arduino/library-registry#adding-a-library-to-library-manager)).

Please feel free to comment here if you have any questions or concerns.
