### ISSUE TITLE
Accidentally wrote the wrong name in library.properties

### ISSUE THREAD

**Issue by cygig** [arduino/library-registry#422]
I misspelled my library as "DailyStrugleButton" instead of "DailyStruggleButton" in library.properties. After the library was live on the library manager, I edited the library.properties and the indexer (http://downloads.arduino.cc/libraries/logs/github.com/cygig/DailyStruggleButton/) doesn't seem too happy with the edited name. What should I do?

**Comment by per1234** [comment]
Hi @cygig. As you noticed, the library is locked to the name it had at the time of the admission to the list. The reason is that this is the sole unique identifier for the library, used by other libraries to specify it as a dependency (e.g., `depends=DailyStruggleButton`, or in CLI commands (e.g., `arduino-cli lib install DailyStruggleButton`) and so changing it can be disruptive to the users. However, we do allow name changes by request. There is less chance for the name change to have an impact in a case like this when the library has not been in Library Manager very long, and so is not likely to have accumulated references to the old name.

The requested change is now in progress. So there is no further action required from you. This issue serves as the name change request.

Unlike submissions, this type of request is still handled manually. The Library Manager index's maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. So you can get a notification if you're following this issue or the relevant PR: https://github.com/arduino/library-registry/pull/423

After that, you can monitor the indexing of the library via its logs web page.

By the way, I very much enjoyed the illustration in your readme!

**Comment by cygig** [comment]
Thank you very much! I am ashamed to say I have little idea of how github works despite being a hobbyist programmer for years. Obviously proofreading and spell checking isn't my strong suit.

**Comment by rsora** [comment]
Solved by #423
