### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by christandlg** [arduino/library-registry#4618]
### Library name

AS3935MI

### Version to remove

1.3.5

**Comment by per1234** [comment]
Hi @christandlg. You must delete the `1.3.5-beta` [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) from the library's BitBucket repository before we can remove the release. I see that it has not yet been removed:

https://bitbucket.org/christandlg/as3935mi/src/1.3.5-beta/library.properties

Once you have removed the tag from the BitBucket repository, comment here to let me know that the tag has been deleted so that I can proceed with removing the release from Arduino Library Manager.

**Comment by christandlg** [comment]
Hi,
the original tag was 1.3.5, i deleted it and created 1.3.5-beta instead. Library version in library.properties is 1.3.5. 
Does the tag still need to be removed?

**Comment by christandlg** [comment]
@per1234 thank you for the clarification. 
I created this issue because library functionality is broken. I will restore the 1.3.5 Tag and create a new release of the lib (with new version number) asap, and hereby cancel my request.
