### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by daguerpedro** [arduino/library-registry#4667]
### Library repository URL

https://github.com/daguerpedro/MQSensor

**Comment by daguerpedro** [comment]
renamed as suggested by the [accepted pr](https://github.com/arduino/library-registry/pull/4666#issuecomment-2166692408) as well as because I still can't access the library through the library manager.

I'm tagging you @per1234  because you've reviewed that pr.

**Comment by per1234** [comment]
Hi @daguerpedro. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

> I still can't access the library through the library manager

You can see the problem here in the library's dedicated logs page:

https://downloads.arduino.cc/libraries/logs/github.com/daguerpedro/MQSensor/

```text
2024/06/14 21:36:01 Scraping https://github.com/daguerpedro/MQSensor.git
2024/06/14 21:36:01 Checking out tag: 1.0.0
2024/06/14 21:36:01 Release MQSensor:1.0.0 has wrong library name, should be MQ Sensor
```

Since it is their sole unique identifier, libraries are locked to the registered name. If the Library Manager indexing system finds a release that has a different name than the registered name, it ignores it.

The library was registered under the value that was present in the `name` property of the `library.properties` metadata file in the latest [tag](https://git-scm.com/docs/git-tag)/[release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository)  at the time you submitted the library. It seems that between the time of the submission and when the hourly indexing job ran after its acceptance, you changed the name, made a new tag/release, and deleted the previous tag (which is something [you should not do](https://git-scm.com/docs/git-tag#_on_re_tagging)). So when the indexer job ran on the library repository it didn't find any releases that had a valid name, and so there are currently no releases to populate Library Manager.

The issue will be resolved once the registered name is updated to match the name in the 1.0.0 release.

**Comment by daguerpedro** [comment]
Ok, thanks for the answer. 
So now I just have to wait for the rename request to be accepted and never re-tag again? Or is there something else that needs to be fixed?

**Comment by per1234** [comment]
> is there something else that needs to be fixed?

No. The change to the registered library name is the only thing that needs to be done. After that, the indexer will pick up your existing 1.0.0 release and any compliant releases you make after that.

**Comment by MatteoPologruto** [comment]
`MQ Sensor` was not found, as expected.
```
2024/06/20 15:48:11 Loaded 7079 libraries from DB
error: Library name MQ Sensor not found
```
