### ISSUE TITLE
No update for library

### ISSUE THREAD

**Issue by RobertByrnes** [arduino/library-registry#4806]
Hi, I have pushed a new tag to master 1.3.0 for GovoroxSSLClient, library.properties file has this version. I have also created the release for this version. This was done on 24 hours ago. The index is not showing this new version and is still on 1.2.0 as the latest.

Is this within a reasonable timeframe or is there an issue with the update process or the way I have used?

Cheers

**Comment by per1234** [comment]
Hi @RobertByrnes. It is present in my Library Manager:

![image](https://github.com/user-attachments/assets/3a30f790-ee19-4533-8975-9bb6e8ad06b1)

It does take some time for a new release to become available to everyone around the world because the index update must work its way through caches. We do give an estimate of availability within one day's time, but it might be that you were just a little too quick.

Please check it again and let us know whether you now see it in your Library Manager.

**Comment by RobertByrnes** [comment]
Hi @per1234 thank you 😊

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
