### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by matsujirushi** [arduino/library-registry#4810]
### Library repository URL

https://github.com/SeeedJP/wio_cellular

**Comment by per1234** [comment]
Hi @matsujirushi. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by matsujirushi** [comment]
Hi,
Should I just wait?

The library name does not appear to have been changed yet.
https://downloads.arduino.cc/libraries/logs/github.com/SeeedJP/wio_cellular/

```
2024/07/24 23:36:34 Checking out tag: 0.1.3
2024/07/24 23:36:34 Release WioCellular:0.1.3 has wrong library name, should be Wio Cellular
```

**Comment by per1234** [comment]
@matsujirushi yes, you must wait.

As I already explained, a manual process must be performed on the index in order to accommodate your request. The change in this repository is only one part of the task. As I said, the issue will be closed once the request is accommodated and GitHub will send you a notification at that time.

We will get to it as soon as we have the time to do so. Until then, please be patient.

**Comment by umbynos** [comment]
Solved in https://github.com/arduino/library-registry/pull/4812#issuecomment-2255911835
