### ISSUE TITLE
Access logs for a gitlab.com hosted project (gitlab.com/painlessmesh/painlessmesh

### ISSUE THREAD

**Issue by BlackEdder** [arduino/library-registry#5331]
### Describe the problem

I was trying to work out why updates in the painlessmesh library were not picked up. Following the FAQ I tried to access the logs here:
https://downloads.arduino.cc/libraries/logs/gitlab.com/painlessmesh/painlessmesh/
but I get an error that the File is not found.

### To reproduce

Click on the following [link](https://downloads.arduino.cc/libraries/logs/gitlab.com/painlessmesh/painlessmesh/) and note that the log file cannot be found.

### Expected behavior

I would expect the link to lead to log files for the library.

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [x] My report contains all necessary details

**Comment by per1234** [comment]
Hi @BlackEdder. The logs URL is case sensitive, so you must make sure the case of the repository slug matches the registry data exactly:

https://github.com/arduino/library-registry/blob/4e61d0984998888677f4f03bc181c4ae3452ada4/registry.txt#L1580

So the slug should be `painlessMesh/painlessMesh` rather than `painlessmesh/painlessmesh` as you used in your URL (note the `M` vs `m`). This means the correct logs URL for the "Painless Mesh" library is:

https://downloads.arduino.cc/libraries/logs/gitlab.com/painlessMesh/painlessMesh/
