### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by YuenNicdao** [arduino/library-registry#5447]
### Library name

iParol

### Version to remove

1.0.0

**Comment by per1234** [comment]
Hi @YuenNicdao . You must delete the 1.0.0 [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) from the library's GitHub repository before we can remove the release. I see that it has not yet been removed.

I'll provide instructions you can follow to do that:

1. Click the following link to open the GitHub page of the tag:
   https://github.com/YuenNicdao/iParol/releases/tag/1.0.0
1. Click the <kbd>**Delete**</kbd> button on that page.
1. Click the <kbd>**I understand, delete this tag**</kbd> button.
1. Comment here to let me know that the tag has been deleted so that I can proceed with removing the release from Arduino Library Manager.

**Comment by per1234** [comment]
For the sake of a tidy repository, I'm going to close this due to lack of activity.

@YuenNicdao if you ever get around to deleting the tag, you are welcome to submit another release removal request.

I'll continue to monitor this thread, so feel free to let me know if you have any questions or concerns.
