### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by h2zero** [arduino/library-registry#5494]
### Library name

NimBLE-Arduino

### Version to remove

2.0.0

**Comment by per1234** [comment]
Hi @h2zero . I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by h2zero** [comment]
Any updates on this? The accidental release is causing some issues for a lot of folks.

**Comment by per1234** [comment]
Hi @h2zero. There is no reason why a delay in removing the release should cause a problem for the users of your library. If you made a bad release, then just fix the problem and then make a new release. This is standard practice in software development.

Arduino Library Manager selects the highest version by default, so if you make a 2.0.1 release then it doesn't matter if there is also a bad 2.0.0 release because the users are going to install 2.0.1. And Library Manager offers updates when a newer version of an installed library, so the new release will also solve the problem for the users who already installed the bad version.

I hope you weren't planning to remove the release and then make a new 2.0.0 release. Using the same version number for two different versions of software is a huge no-no, which is sure to cause confusion for the users, and for you when supporting those users (just imagine having to ask users: "which of the two 2.0.0 versions do you have installed?" 😱). We do not offer the release removal service to allow do-overs. We only offer it for emergency situations when a release contains something that absolutely must be removed from the Internet (e.g., content that violates a copyright).

We will get to removing the release when we find the time to do so. Until then you will just need to be patient.

**Comment by h2zero** [comment]
Thanks @per1234 I was planning to make a new release as 2.1.0 but it's a very large update and is going to take considerable time before it's ready. What happened was I was releasing version 1.4.3 but forgot to change the branch to that release branch beforehand and the library manager picked up the dev branch in which the library version was set to 2.0.0, which is still a WIP. So now I have quite a few issues popping up about this (major API changes). 

Anyway, since it's been out this long already I'll just close this and pin an issue in the repo warning users that it was an accidental release.
