### ISSUE TITLE
[Library Manager] Request for updating library

### ISSUE THREAD

**Issue by 0015** [arduino/library-registry#652]
Library update 1.2.0
Repository: https://github.com/0015/TP_Arduino_DigitalRain_Anim

@ArduinoBot

**Comment by per1234** [comment]
Hi @0015. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically! It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
http://downloads.arduino.cc/libraries/logs/github.com/0015/TP_Arduino_DigitalRain_Anim/

---
The relevant lines of the logs are these:

```
2021/11/09 04:16:04 Checking out tag: 1.2.0
2021/11/09 04:16:04 Release Digital Rain Animation for TFT_eSPI:1.1.1 already loaded, skipping
```

Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that you forgot to update the `version` value in `library.properties` before making the 1.2.0 release:
https://github.com/0015/TP_Arduino_DigitalRain_Anim/blob/1.2.0/library.properties#L2
```
version=1.1.1
```
One of the requirements I mentioned above is that each release must have a unique `version` value. Since this one didn't, it was not indexed. I see you have updated the `version` value since then, but the indexer works only from Git tags, so it can't see that.

The solution is to do this:

1. Update the `version` value in `library.properties` to `1.2.1`:
   ```
   version=1.2.1
   ```
1. Make a 1.2.1 release/Git tag of the library.

Even though the 1.2.0 release won't be in Library Manager, the 1.2.1 release is almost identical, so the version skip won't be an issue for the users.

**Comment by 0015** [comment]
@per1234 Thank you for your kind explanation. I've prepared again as you said, but it's still not being updated. Can you take a look at what the problem is again? Thanks again.
