### ISSUE TITLE
Bolder Flight MPU9250 Library not Updating in Manager

### ISSUE THREAD

**Issue by flybrianfly** [arduino/library-registry#772]
Updated our MPU-9250 and issued new tags.
https://github.com/bolderflight/mpu9250

Not seeing it updated in library manager

**Comment by per1234** [comment]
Hi @flybrianfly. You can see the reason here in the library's dedicated Library Manager logs page:

http://downloads.arduino.cc/libraries/logs/github.com/bolderflight/MPU9250/

```
2021/12/08 20:07:06 Error syncing library: exit status 1
2021/12/08 20:07:06 Checking out tag: v5.2.0
2021/12/08 20:07:06 Arduino Lint found errors:
Click to expand Arduino Lint report

Linting library in /home/ubuntu/workspace/gitclones/github.com/bolderflight/MPU9250
ERROR: .exe file(s) found: /home/ubuntu/workspace/gitclones/github.com/bolderflight/MPU9250/tools/teensy_loader_cli.exe.
       Presence of these files blocks addition to the Library Manager index. (Rule LS007)                               
```

So you will need to remove the executable from the library. Some ideas of places to store this sort of thing:

- [GitHub release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) assets
- Dedicated branch
- Separate repository

You can see the list of requirements for a release to be accepted by the Library Manager indexer here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

If you like, you can set up the repository's CI system to automatically check for compliance on every PR and commit to ensure that releases will always be accepted:

https://github.com/arduino/arduino-lint-action#readme

Or if you prefer to use the tool directly:

https://arduino.github.io/arduino-lint/latest/
