### ISSUE TITLE
Remove releases: Bugtton@1.0.0, Bugtton@1.0.1, Bugtton@1.0.2, Bugtton@1.0.3

### ISSUE THREAD

**Issue by sakabug** [arduino/library-registry#775]
Hi

There was some code missing after heavily editing my code at some point.

I updated https://github.com/sakabug/Bugtton to v1.0.4 and deleted old release tags. I don't know will it update new tag and delete removed tags automatically, but made this to be sure. Everything below v1.0.4 should be gone from the IDE list.

**Comment by per1234** [comment]
Hello @sakabug

>deleted old release tags

The previous tags are still in the repository on GitHub:

https://github.com/sakabug/Bugtton/tags

Maybe you only deleted them from your local repository?

You must delete the tags from GitHub before we can proceed to remove them from the Library Manager index. Otherwise the indexer would just pick them up again within an hour after we removed them from the index.

Please comment here once the tags are deleted.

>will it update new tag and delete removed tags automatically

It does not. Once a release is added to the index, it is stored on Arduino's servers and thus persists through deletion from GitHub. Releases are removed on request so you did the right thing to open an issue.

**Comment by sakabug** [comment]
Oops. Thanks!

**Comment by per1234** [comment]
OK. The requested removal is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue, you'll get a notification at that time.

**Comment by rsora** [comment]
Release removal done!
```
2021/12/17 17:35:47 Loaded 4447 libraries from DB
Removing Bugtton@1.0.0
Success!

2021/12/17 17:35:56 Loaded 4447 libraries from DB
Removing Bugtton@1.0.1
Success!

2021/12/17 17:36:01 Loaded 4447 libraries from DB
Removing Bugtton@1.0.2
Success!

2021/12/17 17:36:05 Loaded 4447 libraries from DB
Removing Bugtton@1.0.3
Success!
```
