### ISSUE TITLE
Rename request of 'Indicator' to 'Blinkenlight' 

### ISSUE THREAD

**Issue by tfeldmann** [arduino/library-registry#800]
Sorry to bother you, but the old name was just meh.

The github URL also changed to [https://github.com/tfeldmann/Arduino-Blinkenlight](https://github.com/tfeldmann/Arduino-Blinkenlight). Should I create a normal pull request for this?

Thanks a lot!

**Comment by rsora** [comment]
Closed after maintenance and merge of #801

**Comment by per1234** [comment]
Hi @tfeldmann. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to the linked issue/PR, you'll get a notification at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

---

This operation is done in two parts:

1. Update of the repository URL list to point to the new URL (https://github.com/arduino/library-registry/pull/801)
   This has been completed.
1. Update of the library's registration data to point to the new URL and to change the name (https://github.com/arduino/library-registry/pull/808).
   This has not been completed.

>Should I create a normal pull request for this?

Submitting the request via this issue is fine. I have produced the necessary PRs on your behalf.

**Comment by tfeldmann** [comment]
Thanks!

**Comment by rsora** [comment]
Closed again after maintenance and merge of #808!
