### ISSUE TITLE
library registry tool kick?

### ISSUE THREAD

**Issue by ladyada** [arduino/library-registry#910]
@cmaglie @per1234 hiya not sure if the library registry cron is running, hasnt seen any updates in a day
https://twitter.com/arduinolibs
wanna take a look?

**Comment by per1234** [comment]
Thanks for the notification @ladyada.

I see here that [the "SdFat - Adafruit Fork"@1.5.1 release](https://github.com/adafruit/SdFat/releases/tag/1.5.1) from 4 hours ago has already been indexed:
https://downloads.arduino.cc/libraries/logs/github.com/adafruit/SdFat/
and it is available for installation via Library Manager:

```
$ arduino-cli lib search "SdFat - Adafruit Fork"
Updating index: library_index.json.gz downloaded ?  19333.12% 00m02ss
Updating index: library_index.json.sig downloaded
Name: "SdFat - Adafruit Fork"
  Author: Bill Greiman <fat16lib@sbcglobal.net>
  Maintainer: Adafruit <support@adafruit.com>
  Sentence: FAT16/FAT32 file system for SD cards and QSPI Flash.
  Paragraph: FAT16/FAT32 file system for SD cards and QSPI Flash.
  Website: https://github.com/adafruit/SdFat
  License: MIT
  Category: Data Storage
  Architecture: rp2040, nrf52, samd, esp32, *
  Types: Contributed
  Versions: [1.2.1, 1.2.3, 1.2.4, 1.3.0, 1.4.0, 1.5.1]
  Dependencies: SD
```

But I see that, in addition to the unexpected lack of activity you observed on [the arduinolibs Twitter feed](https://twitter.com/arduinolibs), it is also not listed on arduino-libraries.info:

https://www.arduinolibraries.info/libraries/sd-fat-adafruit-fork

So maybe the problem is with that system (CC: @njh)?

**Comment by ladyada** [comment]
oh interesting i didnt see there's a way to look at the logs - ill do that next time, usually the arduinolibs is up-to-date :)
