### ISSUE TITLE
[Library Manager] lib update version issues

### ISSUE THREAD

**Issue by Gitshaoxiang** [arduino/library-registry#987]
Hi.  we just update try to release a new tag & version.  
I have tried to delete the tag and release it again.  but seems it still can't update.
could you help me check this problem?

[M5EPD LIB LINK](https://github.com/m5stack/M5EPD)
[M5Atom LIB LINK](https://github.com/m5stack/M5Atom)

![image](https://user-images.githubusercontent.com/45260108/151474096-ee5a4d63-178a-4679-9f18-054c0c190d60.png)

![image](https://user-images.githubusercontent.com/45260108/151474320-bf6f24b2-862b-42c6-90a0-02792c7c59ae.png)

**Comment by per1234** [comment]
Hi @Gitshaoxiang

## Problems

The problem in [the "M5EPD" library's logs](https://downloads.arduino.cc/libraries/logs/github.com/m5stack/M5EPD/):

```
2022/01/28 02:18:49 Checking out tag: 0.1.2
2022/01/28 02:18:49 Release M5EPD:0.1.1 already loaded, skipping
```

Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `0.1.2` tag.
You can see it here:
https://github.com/m5stack/M5EPD/blob/0.1.2/library.properties#L2
```
version=0.1.1
```

Even though Git tags are the unit of release for the Arduino Library Manager, all versioning is done according to the  `version` field of the `library.properties` file. For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

---

[The problem](https://downloads.arduino.cc/libraries/logs/github.com/m5stack/M5Atom/) is the same for the "M5Atom" library:

```
2022/01/28 03:13:57 Checking out tag: 0.0.8
2022/01/28 03:13:57 Release M5Atom:0.0.7 already loaded, skipping
```
https://github.com/m5stack/M5Atom/blob/0.0.8/library.properties#L2
```
version=0.0.7
```

## Solution

The solution is to make another release  of each library which meet [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list):

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day. The non-compliant release will still be missing, but since the newer release will be available, it is no problem.

Please let me know if you have any questions or concerns.
Regards, Per
