### ISSUE TITLE
Correcting name and link of library

### ISSUE THREAD

**Issue by nseidle** [arduino/library-registry#998]
Hi - I need to change the name of an existing library.

https://github.com/sparkfun/SparkFun_Si701_Breakout_Arduino_Library

Became

https://github.com/sparkfun/SparkFun_Si7021_Arduino_Library

library.properties has been updated and a release made.

I can do a PR with the name correction but it's not clear from [the docs](https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-my-librarys-name) if a PR is required, or just the issue raise.

**Comment by per1234** [comment]
Hi @nseidle. Although we require submissions to be made via PRs (in order to take advantage of the automated submissions handling system), it is fine to make registry maintenance requests like this by submitting an issue.

The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and will close this request issue when that is done.

**Comment by nseidle** [comment]
Thanks per1234. The new automated lib process is a great improvement. I wish there was a 'buy me a coffee' jar for the 'Library Manager index maintainer' since it was our mistake. I worry we have another ~5 repos that need renaming. If there's anything we can do to make it easier, please let me know.

**Comment by per1234** [comment]
>I wish there was a 'buy me a coffee' jar for the 'Library Manager index maintainer'

Haha. @umbynos is taking that role lately and surely deserving some coffee breaks for this excellent work.

>I worry we have another ~5 repos that need renaming.

No worries. We have the system very streamlined now and are always happy to help out in the maintenance of this amazing resource created through the work of the entire Arduino community.

> If there's anything we can do to make it easier, please let me know.

The issues are just fine. We strive to make the system as simple for the library maintainers to use as possible.

---

If you are interested in the boring details. You can see the changes in this repository made to accommodate this request here:

- https://github.com/arduino/library-registry/pull/999
- https://github.com/arduino/library-registry/pull/1000

The file `repositories.txt` in the repository's `main` branch is used to allow submissions to be made to a simple list of repository URLs, but some additional registration data must be recorded at the time of submission. That data are recorded in the file `registry.txt` in the `production` branch. Two PRs are used due to the files being in different branches.

So it is a quick and simple operation for someone familiar with the system like me, but the library maintainer's time would most likely be better spent on their library. But of course people are welcome to submit PRs directly if they prefer that approach.

**Comment by nseidle** [comment]
Ahah! I didn't think to look for a production branch. I may try a PR in the future.

Thanks @per1234 and @umbynos! We're seeing it now in the lib manager.
